version: "3.7"

services:
  mind-map:
    build: .
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      MONGODB_HOSTS: mongo:27017
      MONGODB_DATABASE: mind-map
      MONGODB_USERNAME: user-test
      MONGODB_PASSWORD: test-password
      MONGODB_SSL: "false"
    networks:
      testvln:
        aliases:
          - mind-map

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mind-map
    networks:
      testvln:
        aliases:
          - mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  testvln:
    driver: bridge